# Generated by Django 5.1.2 on 2024-10-22 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_alter_todo_completed_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='created_date',
            new_name='createddate',
        ),
    ]
