# Generated by Django 5.1.2 on 2024-10-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0005_remove_todo_completed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='ceated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
