# Generated by Django 5.1.2 on 2024-10-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0007_alter_todo_ceated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='ceated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
