# Generated by Django 5.1.2 on 2024-10-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0012_alter_todo_ceated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('completed', 'complted'), ('pending', 'pending')], default='pending', max_length=250),
        ),
    ]
