# Generated by Django 5.1.2 on 2024-10-22 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0013_alter_todo_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='ceated_date',
            new_name='created_date',
        ),
    ]
