# Generated by Django 5.1.2 on 2024-10-22 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0014_rename_ceated_date_todo_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='date_end',
            new_name='datecompleted',
        ),
    ]
