# Generated by Django 5.1.2 on 2024-10-22 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0015_rename_date_end_todo_datecompleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='datecompleted',
            new_name='date_end',
        ),
    ]
