# Generated by Django 5.1.2 on 2024-10-22 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0016_rename_datecompleted_todo_date_end'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='date_end',
            new_name='datecompleted',
        ),
    ]
